name: ReactYarn CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: self-hosted

    steps:
    
    - run: |
        cd "C:\TestFYP\ReactAppYarn\confusion"
        $env:HOST = 'localhost'
        yarn start





