name: ReactYarn CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Launch Docker Desktop
      run: cd "C:\Program Files\Docker\Docker"; ".\Docker Desktop.exe"
      
    - name: Install yarn
      run: npm install -g yarn
    
    - name: Build yarn
      run: yarn install
    
    - name: Start yarn (Launch Website)
      run: $env:HOST = 'localhost'; cmd.exe /c start yarn start 
    
    - name: Build with Maven
      run: cd "C:\TestFYP\HealeniumTests"; mvn -B package --file pom.xml
    
    - name: Test with Maven
      run: cd "C:\TestFYP\HealeniumTests"; mvn test -Dtest=Healing 
      
    - name: Kill yarn
      run: taskkill -F -IM node.exe
