name: ReactYarn CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build_yarn:

    name: Building Yarn
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install yarn
      run: npm install -g yarn
    
    - name: Build yarn
      run: yarn install
    
    
  start_yarn:

    name: Starting Yarn
    runs-on: self-hosted
    
    steps:
    - name: Start yarn (Launch Website)
      run: $env:HOST = 'localhost'; yarn start
      
  docker_start:

    name: Launching Docker Desktop
    runs-on: self-hosted
    
    steps:
    - name: Launch Docker Desktop
      run: cd "C:\Program Files\Docker\Docker"; "Docker Desktop.exe" 
    
  maven:
  
    name: Maven 
    needs: build_yarn
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build with Maven
      run: cd "C:\TestFYP\HealeniumTests"; mvn -B package --file pom.xml
    
    - name: Test with Maven
      run: cd "C:\TestFYP\HealeniumTests"; mvn -Dtest=Healing 
      
    - name: Kill yarn
      run: taskkill -F -IM node.exe
